[project]
name = "bank-accounts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "fastapi[standard]>=0.115.12",
    "field>=0.2.0",
    "pydantic>=2.11.5",
    "typing>=3.10.0.0",
]
